"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckSquare2, Link2, Megaphone, Plus, Save, UsersRound } from "lucide-react";
import { flushPendingTeamSection, saveTeamSection, type SyncStatus } from "@/lib/client/team-sync";

type Announcement={id:string;title:string;body:string;createdAt:string};
type TeamEvent={id:string;title:string;date:string;time:string;location:string};
type Poll={id:string;question:string;options:{id:string;label:string;votes:number}[]};
type Availability={id:string;date:string;status:"YES"|"MAYBE"|"NO";note:string};
type Resource={id:string;label:string;url:string};
type TeamOps={announcements:Announcement[];events:TeamEvent[];polls:Poll[];availability:Availability[];resources:Resource[]};
function validUrl(value:string){try{const u=new URL(value);return u.protocol==="https:"||u.protocol==="http:";}catch{return false;}}

export function CommunityHub({teamId,teamName,initialState}:{teamId:string;teamName:string;initialState:Record<string,unknown>}){
  const initial=initialState as Partial<TeamOps>;
  const [state,setState]=useState<TeamOps>({announcements:Array.isArray(initial.announcements)?initial.announcements:[],events:Array.isArray(initial.events)?initial.events:[],polls:Array.isArray(initial.polls)?initial.polls:[],availability:Array.isArray(initial.availability)?initial.availability:[],resources:Array.isArray(initial.resources)?initial.resources:[]});
  const [sync,setSync]=useState<SyncStatus>("saved");
  const [announcement,setAnnouncement]=useState({title:"",body:""});
  const [event,setEvent]=useState({title:"",date:"",time:"",location:""});
  const [poll,setPoll]=useState({question:"",options:""});
  const [availability,setAvailability]=useState<{date:string;status:"YES"|"MAYBE"|"NO";note:string}>({date:"",status:"YES",note:""});
  const [resource,setResource]=useState({label:"",url:""});
  useEffect(()=>{void flushPendingTeamSection(teamId,"teamOps").then(r=>r&&setSync(r));},[teamId]);
  function persist(next:TeamOps){setState(next);setSync("saving");void saveTeamSection(teamId,"teamOps",next).then(setSync);}
  function addAnnouncement(){if(!announcement.title.trim()||!announcement.body.trim())return;persist({...state,announcements:[{id:crypto.randomUUID(),title:announcement.title.trim(),body:announcement.body.trim(),createdAt:new Date().toISOString()},...state.announcements]});setAnnouncement({title:"",body:""});}
  function addEvent(){if(!event.title.trim()||!event.date)return;persist({...state,events:[...state.events,{id:crypto.randomUUID(),title:event.title.trim(),date:event.date,time:event.time,location:event.location.trim()}].sort((a,b)=>a.date.localeCompare(b.date))});setEvent({title:"",date:"",time:"",location:""});}
  function addPoll(){const options=poll.options.split("\n").map(x=>x.trim()).filter(Boolean).slice(0,8);if(!poll.question.trim()||options.length<2)return;persist({...state,polls:[{id:crypto.randomUUID(),question:poll.question.trim(),options:options.map(label=>({id:crypto.randomUUID(),label,votes:0}))},...state.polls]});setPoll({question:"",options:""});}
  function vote(pollId:string,optionId:string){persist({...state,polls:state.polls.map(p=>p.id===pollId?{...p,options:p.options.map(o=>o.id===optionId?{...o,votes:o.votes+1}:o)}:p)});}
  function addAvailability(){if(!availability.date)return;persist({...state,availability:[{id:crypto.randomUUID(),...availability},...state.availability]});setAvailability({date:"",status:"YES",note:""});}
  function addResource(){if(!resource.label.trim()||!validUrl(resource.url))return;persist({...state,resources:[...state.resources,{id:crypto.randomUUID(),label:resource.label.trim(),url:resource.url.trim()}]});setResource({label:"",url:""});}
  const nextEvents=useMemo(()=>state.events.slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,8),[state.events]);
  return <section className="workspace-page suite-page"><header className="suite-hero compact"><div><div className="suite-badges"><span className="analysis-badge">PRIVATE TEAM WORKSPACE</span><span className={`status-chip ${sync==="saved"?"good":"neutral"}`}>{sync==="saved"?"Shared with team":sync==="saving"?"Saving…":"Offline cache"}</span></div><p className="page-kicker">Team Hub · {teamName}</p><h1>Run practice like a robotics team, not a group chat.</h1><p>Announcements, practice dates, availability, polls and shared links stay with the selected team. Use Tasks for assigned engineering work.</p></div><a href="/team/tasks" className="button button-primary"><CheckSquare2 size={14}/> Open tasks</a></header>
    <div className="team-hub-grid"><section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Announcements</span><h2>Post a team update</h2></div><Megaphone size={18}/></div><div className="form-grid"><label>Title<input value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/></label><label>Message<textarea value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/></label></div><button className="button button-primary" onClick={addAnnouncement}><Plus size={14}/> Post</button><div className="hub-feed">{state.announcements.map(a=><article key={a.id}><span>{new Date(a.createdAt).toLocaleString()}</span><h3>{a.title}</h3><p>{a.body}</p></article>)}{!state.announcements.length?<div className="suite-empty">No announcements yet.</div>:null}</div></section>
      <section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Practice calendar</span><h2>Team dates</h2></div><CalendarDays size={18}/></div><div className="form-grid"><label>Title<input value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/></label><div className="form-grid two-col"><label>Date<input type="date" value={event.date} onChange={e=>setEvent({...event,date:e.target.value})}/></label><label>Time<input type="time" value={event.time} onChange={e=>setEvent({...event,time:e.target.value})}/></label></div><label>Location / note<input value={event.location} onChange={e=>setEvent({...event,location:e.target.value})}/></label></div><button className="button button-primary" onClick={addEvent}><Plus size={14}/> Add date</button><div className="hub-feed compact">{nextEvents.map(e=><article key={e.id}><strong>{e.date}{e.time?` · ${e.time}`:""}</strong><h3>{e.title}</h3><p>{e.location||"No location recorded"}</p></article>)}{!nextEvents.length?<div className="suite-empty">No team dates yet.</div>:null}</div></section></div>
    <div className="team-hub-grid"><section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Availability</span><h2>Can you make practice?</h2></div><UsersRound size={18}/></div><div className="form-grid two-col"><label>Date<input type="date" value={availability.date} onChange={e=>setAvailability({...availability,date:e.target.value})}/></label><label>Status<select value={availability.status} onChange={e=>setAvailability({...availability,status:e.target.value as "YES"|"MAYBE"|"NO"})}><option value="YES">Available</option><option value="MAYBE">Maybe</option><option value="NO">Unavailable</option></select></label><label className="span-2">Note<input value={availability.note} onChange={e=>setAvailability({...availability,note:e.target.value})}/></label></div><button className="button button-quiet" onClick={addAvailability}><Save size={14}/> Save availability</button><div className="availability-list">{state.availability.slice(0,12).map(a=><div key={a.id}><strong>{a.date}</strong><span className={`status-chip ${a.status==="YES"?"good":"neutral"}`}>{a.status.toLowerCase()}</span><small>{a.note||"No note"}</small></div>)}</div></section>
      <section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Polls</span><h2>Make a quick decision</h2></div></div><div className="form-grid"><label>Question<input value={poll.question} onChange={e=>setPoll({...poll,question:e.target.value})}/></label><label>Options <small>one per line</small><textarea value={poll.options} onChange={e=>setPoll({...poll,options:e.target.value})}/></label></div><button className="button button-quiet" onClick={addPoll}><Plus size={14}/> Create poll</button><div className="poll-list">{state.polls.map(p=><article key={p.id}><strong>{p.question}</strong>{p.options.map(o=><button type="button" key={o.id} onClick={()=>vote(p.id,o.id)}><span>{o.label}</span><b>{o.votes}</b></button>)}</article>)}</div></section></div>
    <section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Shared resources</span><h2>Links the team actually needs</h2></div><Link2 size={18}/></div><div className="resource-add-row"><input aria-label="Resource label" value={resource.label} onChange={e=>setResource({...resource,label:e.target.value})} placeholder="Label"/><input aria-label="Resource URL" value={resource.url} onChange={e=>setResource({...resource,url:e.target.value})} placeholder="https://"/><button className="button button-primary" onClick={addResource}>Add link</button></div><div className="resource-list">{state.resources.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer"><Link2 size={14}/><span>{r.label}</span><small>{r.url}</small></a>)}</div></section>
  </section>;
}
