"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Plus, RotateCw, ShieldCheck, TimerReset } from "lucide-react";
import { flushPendingTeamSection, saveTeamSection, type SyncStatus } from "@/lib/client/team-sync";

type Robot = { id: string; name: string; configuration: null | { configurationVersion: number; mechanisms: { id: string; name: string; type: string }[] } };
type Run = { id: string; robotId: string; revision: number; route: string; time: number; success: boolean; score: number | null; note: string; createdAt: string };
type Cycle = { id: string; robotId: string; revision: number; mechanism: string; mechanismVersion: string; success: boolean; note: string; createdAt: string };
type TestingState = { runs: Run[]; cycles: Cycle[] };

export function TestingCenter({ teamId, activeRobotId, robots, initialState }: { teamId: string; activeRobotId: string | null; robots: Robot[]; initialState: Record<string, unknown> }) {
  const initial: TestingState = { runs: Array.isArray((initialState as { runs?: unknown }).runs) ? (initialState as unknown as TestingState).runs : [], cycles: Array.isArray((initialState as { cycles?: unknown }).cycles) ? (initialState as unknown as TestingState).cycles : [] };
  const [state, setState] = useState(initial);
  const [robotId, setRobotId] = useState(activeRobotId ?? robots[0]?.id ?? "");
  const [sync, setSync] = useState<SyncStatus>("saved");
  const [route, setRoute] = useState(""); const [time, setTime] = useState(""); const [score, setScore] = useState(""); const [result, setResult] = useState<""|"pass"|"fail">(""); const [note, setNote] = useState("");
  const [mechanism, setMechanism] = useState(""); const [mechanismVersion, setMechanismVersion] = useState(""); const [cycleNote, setCycleNote] = useState("");
  const robot = robots.find((r)=>r.id===robotId) ?? null; const revision = robot?.configuration?.configurationVersion ?? 0;
  useEffect(()=>{ void flushPendingTeamSection(teamId,"testing").then((s)=>s&&setSync(s)); },[teamId]);
  function persist(next: TestingState){ setState(next); setSync("saving"); void saveTeamSection(teamId,"testing",next).then(setSync); }
  const runs = state.runs.filter((r)=>r.robotId===robotId && r.revision===revision);
  const cycles = state.cycles.filter((c)=>c.robotId===robotId && c.revision===revision);
  const successRate = runs.length ? runs.filter((r)=>r.success).length/runs.length*100 : null;
  const avgTime = runs.length ? runs.reduce((s,r)=>s+r.time,0)/runs.length : null;
  const scored = runs.filter((r)=>r.score!==null); const avgScore = scored.length ? scored.reduce((s,r)=>s+(r.score??0),0)/scored.length : null;
  const mechanismStats = useMemo(()=>{ const map=new Map<string,{success:number,total:number}>(); for(const c of cycles){ const key=`${c.mechanism} · ${c.mechanismVersion||"unversioned"}`; const current=map.get(key)??{success:0,total:0}; current.total++; if(c.success) current.success++; map.set(key,current);} return [...map.entries()].sort((a,b)=>a[1].success/a[1].total-b[1].success/b[1].total); },[cycles]);
  function addRun(){ const t=Number(time); if(!robotId||!route.trim()||!Number.isFinite(t)||t<=0||!result)return; const s=score.trim()===""?null:Number(score); persist({ ...state, runs:[{id:crypto.randomUUID(),robotId,revision,route:route.trim(),time:t,success:result==="pass",score:Number.isFinite(s)?s:null,note:note.trim(),createdAt:new Date().toISOString()},...state.runs]}); setRoute("");setTime("");setScore("");setResult("");setNote(""); }
  function addCycle(ok:boolean){ if(!robotId||!mechanism.trim())return; persist({ ...state, cycles:[{id:crypto.randomUUID(),robotId,revision,mechanism:mechanism.trim(),mechanismVersion:mechanismVersion.trim(),success:ok,note:cycleNote.trim(),createdAt:new Date().toISOString()},...state.cycles]}); setCycleNote(""); }

  return <section className="workspace-page suite-page"><header className="suite-hero compact"><div><div className="suite-badges"><span className="analysis-badge"><Activity size={13}/> TEST EVIDENCE</span><span className={`status-chip ${sync==="saved"?"good":"neutral"}`}>{sync==="saved"?"Shared with team":sync==="saving"?"Saving…":"Offline cache"}</span></div><p className="page-kicker">Testing</p><h1>Reliability belongs to a robot revision.</h1><p>Tests are separated by robot and saved configuration revision, so an old intake or drivetrain does not contaminate new reliability numbers.</p></div></header>
    <section className="suite-panel"><label className="robot-select-label">Robot<select value={robotId} onChange={(e)=>setRobotId(e.target.value)}><option value="">Select robot</option>{robots.map((r)=><option key={r.id} value={r.id}>{r.id===activeRobotId?"★ ":""}{r.name}</option>)}</select></label>{robot?<p className="form-helper">Current configuration revision: <strong>v{revision || "unconfigured"}</strong>. New records are attached to this revision.</p>:null}</section>
    <div className="test-kpis"><div><span>AUTO SUCCESS</span><strong>{successRate===null?"—":`${successRate.toFixed(0)}%`}</strong><small>{runs.length?`${runs.length} runs on v${revision}`:"No runs"}</small></div><div><span>AVG. AUTO TIME</span><strong>{avgTime===null?"—":`${avgTime.toFixed(2)}s`}</strong><small>Current revision only</small></div><div><span>AVG. TEST SCORE</span><strong>{avgScore===null?"—":avgScore.toFixed(1)}</strong><small>Recorded scores only</small></div><div><span>PRIORITY</span><strong>{mechanismStats[0]?.[0]??"—"}</strong><small>{mechanismStats[0]?`${(mechanismStats[0][1].success/mechanismStats[0][1].total*100).toFixed(1)}% clean`:"Record cycles"}</small></div></div>
    <div className="strategy-grid"><section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Autonomous run logger</span><h2>Record a tested route</h2></div><TimerReset size={18}/></div><div className="form-grid two-col"><label>Route<input value={route} onChange={(e)=>setRoute(e.target.value)}/></label><label>Time (s)<input type="number" min="0.01" step="0.01" value={time} onChange={(e)=>setTime(e.target.value)}/></label><label>Score (optional)<input type="number" value={score} onChange={(e)=>setScore(e.target.value)}/></label><label>Result<select value={result} onChange={(e)=>setResult(e.target.value as typeof result)}><option value="">Select</option><option value="pass">Successful</option><option value="fail">Failed</option></select></label><label className="span-2">Observation<textarea value={note} onChange={(e)=>setNote(e.target.value)}/></label></div><button className="button button-primary" type="button" onClick={addRun} disabled={!robot}><Plus size={14}/> Add test run</button></section>
      <section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Mechanism cycles</span><h2>Record a pass or failure</h2></div><RotateCw size={18}/></div><div className="form-grid"><label>Mechanism<input list="mechanism-options" value={mechanism} onChange={(e)=>setMechanism(e.target.value)}/><datalist id="mechanism-options">{robot?.configuration?.mechanisms.map((m)=><option key={m.id} value={m.name}/>)}</datalist></label><label>Mechanism version<input value={mechanismVersion} onChange={(e)=>setMechanismVersion(e.target.value)} placeholder="e.g. V2"/></label><label>Note<textarea value={cycleNote} onChange={(e)=>setCycleNote(e.target.value)}/></label></div><div className="device-add-actions"><button className="button button-quiet" type="button" onClick={()=>addCycle(true)}><CheckCircle2 size={14}/> Pass</button><button className="button button-quiet fail-button" type="button" onClick={()=>addCycle(false)}>Fail</button></div>{mechanismStats.map(([name,stat])=><div className="mechanism-row" key={name}><div><strong>{name}</strong><span>{stat.success}/{stat.total} successful · {(stat.success/stat.total*100).toFixed(1)}%</span></div></div>)}</section></div>
    <section className="suite-panel"><div className="suite-panel-heading"><div><span className="section-overline">Recent evidence</span><h2>Autonomous history</h2></div><ShieldCheck size={18}/></div><div className="run-table"><div className="run-row head"><span>Route</span><span>Time</span><span>Score</span><span>Result</span><span>Notes</span></div>{runs.slice(0,12).map((r)=><div className="run-row" key={r.id}><strong>{r.route}</strong><span>{r.time.toFixed(2)}s</span><span>{r.score??"—"}</span><span className={r.success?"pass-text":"fail-text"}>{r.success?"PASS":"FAIL"}</span><small>{r.note||"—"}</small></div>)}{!runs.length?<div className="suite-empty">No tests for this robot revision yet.</div>:null}</div></section>
  </section>;
}
